// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TypicalTechTools.Models.Data;

#nullable disable

namespace TypicalTechTools.Migrations
{
    [DbContext(typeof(TTDBContext))]
    partial class TTDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TypicalTechTools.Models.Product", b =>
                {
                    b.Property<int>("ProductCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCode"));

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductCode");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductCode = 12345,
                            ProductDescription = "bluetooth headphones with fair battery life and a 1 month warranty",
                            ProductName = "Generic Headphones",
                            ProductPrice = 84.99m,
                            Updated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4823)
                        },
                        new
                        {
                            ProductCode = 12346,
                            ProductDescription = "bluetooth headphones with good battery life and a 6 month warranty",
                            ProductName = "Expensive Headphones",
                            ProductPrice = 149.99m,
                            Updated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4843)
                        },
                        new
                        {
                            ProductCode = 12347,
                            ProductDescription = "bluetooth headphones with good battery life and a 12 month warranty",
                            ProductName = "Name Brand Headphones",
                            ProductPrice = 199.99m,
                            Updated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4844)
                        },
                        new
                        {
                            ProductCode = 12348,
                            ProductDescription = "simple bluetooth pointing device",
                            ProductName = "Generic Wireless Mouse",
                            ProductPrice = 39.99m,
                            Updated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4845)
                        },
                        new
                        {
                            ProductCode = 12349,
                            ProductDescription = "mouse and keyboard wired combination",
                            ProductName = "Logitach Mouse and Keyboard",
                            ProductPrice = 73.99m,
                            Updated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4846)
                        },
                        new
                        {
                            ProductCode = 12350,
                            ProductDescription = "quality wireless mouse",
                            ProductName = "Logitach Wireless Mouse",
                            ProductPrice = 149.99m,
                            Updated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4847)
                        });
                });

            modelBuilder.Entity("TypicalTechTools.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductCode");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            ProductCode = 12345,
                            ReviewCreated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4963),
                            ReviewText = "This is a great product. Highly Recommended."
                        },
                        new
                        {
                            ReviewId = 2,
                            ProductCode = 12350,
                            ReviewCreated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4967),
                            ReviewText = "Not worth the excessive price. Stick with a cheaper generic one."
                        },
                        new
                        {
                            ReviewId = 3,
                            ProductCode = 12345,
                            ReviewCreated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4968),
                            ReviewText = "A great budget buy. As good as some of the expensive alternatives."
                        },
                        new
                        {
                            ReviewId = 4,
                            ProductCode = 12347,
                            ReviewCreated = new DateTime(2026, 4, 6, 17, 45, 46, 199, DateTimeKind.Local).AddTicks(4969),
                            ReviewText = "Total garbage. Never buying this brand again!"
                        });
                });

            modelBuilder.Entity("TypicalTechTools.Models.Review", b =>
                {
                    b.HasOne("TypicalTechTools.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
